// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://twyskqhuxzqzclzoejmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3eXNrcWh1eHpxemNsem9lam1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0ODQyOTgsImV4cCI6MjA2NTA2MDI5OH0.Yc_4RFtfc7Anu8GyPWCHO6f3I3KBfiV7czF39qSvHuk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);